"""add previous_body_markdown for basic version rollback

Revision ID: 33cef8582209
Revises: ca124ecf754b
Create Date: 2026-08-02 16:57:32.810211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cef8582209'
down_revision: Union[str, Sequence[str], None] = 'ca124ecf754b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('previous_body_markdown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'previous_body_markdown')
    # ### end Alembic commands ###
