"""add product_version field to articles

Revision ID: 59bdb6e4fd25
Revises: 33cef8582209
Create Date: 2026-08-03 13:02:17.933240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59bdb6e4fd25'
down_revision: Union[str, Sequence[str], None] = '33cef8582209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('product_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'product_version')
    # ### end Alembic commands ###
