"""add audit_logs, previous_body_markdown, product_version, media

Revision ID: 8b597c4e3bcb
Revises: 0d9bb186f0e6
Create Date: 2026-08-08 11:25:34.471738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b597c4e3bcb'
down_revision: Union[str, Sequence[str], None] = '0d9bb186f0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
